const menu = [
  {
    id: 1,
    title: "Paneer Butter Masala",
    category: "Lunch",
    veg: true,
    mealCourse: "in main course",
    price: 15.99,
    img: "./images/Item1.jpg",
    total_reviews: 109,
    stars: 4.9,
    description:
      "This Paneer Butter Masala recipe is a rich and creamy dish of paneer (cottage cheese) in a tomato, butter and cashew sauce (known as Makhani gravy).",
  },
  {
    id: 2,
    title: "Veg Extravaganza",
    category: "Breakfast",
    veg: true,
    mealCourse: "In breakfast",
    price: 319,
    img: "./images/Veg Extravaganza.jpg",
    total_reviews: 80,
    stars: 3.5,
    description:
      "Black olives, capsicum, onion, grilled mushroom, corn, tomato, jalapeno & extra cheese",
  },
  {
    id: 3,
    title: "Cocktail Fruit Crunch Salad",
    category: "Breakfast",
    veg: true,
    mealCourse: "in breakfast",
    price: 349,
    img: "./images/Cocktail Fruit Crunch Salad.jpg",
    total_reviews: 108,
    stars: 4.3,
    description:
      "Assorted lettuce, sun melon, red apple, oranges, pineapple, cherries, grapes, kiwi, topped with cottage cheese, pomegranate, crunchy walnut, along with fruity Greek yogurt dressing and seasonings.",
  },
  {
    id: 4,
    title: "Chicken Caesar Salad",
    category: "Breakfast",
    veg: false,
    mealCourse: "in breakfast",
    price: 299,
    img: "./images/Chicken Caesar Salad.jpg",
    total_reviews: 98,
    stars: 4.8,
    description:
      "Lettuce, mixed bell peppers, chicken, cherry tomatoes, red cabbage, onion, black olives, and parsley along with housemade croutons, and house caesar yogurt dressing.",
  },
  {
    id: 5,
    title: "Shahi Paneer with 2 Paratha and Salad",
    category: "Lunch",
    veg: true,
    mealCourse: "in main course",
    price: 110,
    img: "./images/Item1.jpg",
    total_reviews: 119,
    stars: 3.5,
    description:
      "This Shahi Paneer is deliciously rich and creamy, making it one of the most popular recipes in Mughlai cuisine.",
  },
  {
    id: 6,
    title: "Simple Dal Khichdi",
    category: "Lunch",
    veg: true,
    mealCourse: "in main course",
    price: 180,
    img: "./images/Simple Dal Khichdi.jpg",
    total_reviews: 174,
    stars: 4.7,
    description:
      "Keeping it simple is the new cool! So is our simple dal khichdi - a perfect, easily digestible meal for anytime, anyday! Allergen information: Traces of mushroom and celery",
  },
  {
    id: 7,
    title: "Indian Non Veg Thali",
    category: "Lunch",
    veg: false,
    mealCourse: "in main course",
    price: 415,
    img: "./images/Indian Non Veg Thali.jpg",
    total_reviews: 51,
    stars: 3.6,
    description:
      "Dal Makhani, 2pc Butter Chicken Boneless , 2 Pcs Chicken Seekh Kebab, Steam Rice , Raita Mix, 2 Lacha Parantha, 1pc Gulab Jamun.",
  },
  {
    id: 8,
    title: "Hyderabadi Dumpukht Biryani [Chicken]",
    category: "Lunch",
    veg: false,
    mealCourse: "in main course",
    price: 739,
    img: "./images/Biryani.jpg",
    total_reviews: 15,
    stars: 2.5,
    description: "[Served In Handi With Mirch Ka Salan & Boorani Raita]",
  },
  {
    id: 9,
    title: "Butterscotch Shake",
    category: "Shakes",
    veg: true,
    mealCourse: "in drinks",
    price: 70,
    img: "./images/Butterscotch Shake.jpg",
    total_reviews: 44,
    stars: 2.5,
    description:
      "Butterscotch Milkshake is a flavourful, wonderful drink made by blending milk, butterscotch flavours & ice cream (optional) and served chilled.",
  },
  {
    id: 10,
    title: "Chocolate Shake",
    category: "Shakes",
    veg: true,
    mealCourse: "in drinks",
    price: 80,
    img: "./images/Chocolate Shake.jpg",
    total_reviews: 163,
    stars: 4.8,
    description:
      "Divine taste of rich and creamy milkshake prepared with this recipe as flavor of its three simple ingredients; milk, chocolate syrup and ice cream is enhanced by whipped cream.",
  },
]

export default menu
